enable-debug: true

version: 1.2.0 #不要触碰

general-settings:
  #是否使用自定义方块作为载体
  use-custom-blocks: false
  #自定义方块名称
  custom-blocks-namespace: "itemsAdders:cooking_port"
  #是否使用原版方块作为载体
  use-vanilla-blocks: true
  #原版方块物品名称
  vanilla-blocks-names: CAULDRON
  #储存方框内信息配方的方式 1.14以上 使用 blockdata 1.14以下使用database 通用 nbtdata
  block-data-storage-type: blockdata

recipes-settings:
  #是否启用配方制作时间
  enable-recipes-time: true
  #检查冲突配方 (占用部分资源)
  check-conflict-recipes: false
  #打碎载体方块是否返回内部物品
  break-block-return-items: true

experimental-settings:
  #使用异步去核对配方
  match-recipes-asynchronous: false
gui-settings:
  gui-name: "厨艺锅"
  first-input-slot: 11
  second-input-slot: 20
  third-input-slot: 29
  fourth-input-slot: 38
  start-button: 40
  recipes-button: 13
  miscellaneous-slots: 42