enable-debug: true

version: 1.2.0 #不要触碰

general-settings:
  #是否使用自定义方块作为载体
  use-custom-blocks: false
  #自定义方块名称
  custom-blocks-namespace: "ItemsAdder:cooking-port"
  #是否使用原版方块作为载体
  use-vanilla-blocks: true
  #原版方块物品名称
  vanilla-blocks-names: CAULDRON
  #储存方框内信息配方的方式 1.14以上 使用 blockdata 1.14以下使用database 通用 nbtdata
  block-data-storage-type: blockdata

recipes-settings:
  #是否启用配方制作时间
  enable-recipes-time: true
  #检查冲突配方 (占用部分资源)
  check-conflict-recipes: false
  #打碎载体方块是否返回内部物品
  break-block-return-items: true
  #是否启用矿物词典模式 (实验性)
  enable-dictionary: false
experimental-settings:
  #使用异步去核对配方
  match-recipes-asynchronous: false
  #使用异步去加载GUI内部组件
  load-gui-asynchronous: false
gui-settings:
  gui-name: "厨艺锅"
  first-input-slot: 10
  second-input-slot: 19
  third-input-slot: 28
  fourth-input-slot: 37
  output-slot: 22
  start-button:
    Material: OAK_BUTTON
    slot: 43
    custom-model-data: 1001
  recipes-button:
    Material: KNOWLEDGE_BOOK
    slot: 25
    custom-model-data: 1002
  process-slot: 40
  filled-item: GRAY_STAINED_GLASS_PANE
gui-state-process-settings:
  #是否开始以烹饪进度百分比来设置状态物品
  enable-percent-state-item: false
  percent-state-settings:
    1:
      scope: 0-5
      Material: PAPER
      custom-model-data: 2000
    2:
      scope: 6-10
      Material: PAPER
      custom-model-data: 2001
  discontinuous-state-settings:
    ready:
      Material: GREEN_STAINED_GLASS_PANE
      custom-model-data: 1003
    processing:
      Material: ORANGE_STAINED_GLASS_PANE
      custom-model-data: 1004